-- Création de la table TRACK_ETIQ
CREATE TABLE IF NOT EXISTS TRACK_ETIQ (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DATE_TIME DATETIME,
    NUM_ETIQ VARCHAR,
    ID_ANTENNE VARCHAR
);

-- Création de la table ETIQ_PC
CREATE TABLE IF NOT EXISTS ETIQ_PC (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NUM_ETIQ VARCHAR,
    NUM_PC VARCHAR,
    DATE_DEBUT DATE,
    DATE_FIN DATE
);

-- Création de la table ANTENNE
CREATE TABLE IF NOT EXISTS ANTENNE (
    ID INTEGER PRIMARY KEY,
    ID_ANTENNE VARCHAR,
    EMPLACEMENT VARCHAR
    DATE_DEBUT DATE,
    DATE_FIN DATE

);
