--commande de création de la DB "sqlite3 TRACK_EYE.db < creation_tables.sql"

-- Création de la table TRACK_ETIQ
CREATE TABLE IF NOT EXISTS TRACK_ETIQ (
    ID INTEGER PRIMARY KEY,
    DATE_TIME DATETIME,
    NUM_ETIQ VARCHAR,
    ID_ANTENNE VARCHAR
);

-- Création de la table ETIQ_PC
CREATE TABLE IF NOT EXISTS ETIQ_PC (
    ID INTEGER PRIMARY KEY,
    NUM_ETIQ VARCHAR,
    NUM_PC VARCHAR,
    DATE_DEBUT DATE,
    DATE_FIN DATE
);

-- Création de la table ANTENNE
CREATE TABLE IF NOT EXISTS ANTENNE (
    ID INTEGER PRIMARY KEY,
    ID_ANTENNE VARCHAR,
    EMPLACEMENT VARCHAR,
    DATE_DEBUT DATE,
    DATE_FIN DATE
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255)
);

-- Insertion de données dans la table TRACK_ETIQ
INSERT INTO TRACK_ETIQ (DATE_TIME, NUM_ETIQ, ID_ANTENNE) VALUES 
('2022-01-01 00:00:00', 'ETIQ1', 'ANT1'),
('2022-01-02 00:00:00', 'ETIQ2', 'ANT2');

-- Insertion de données dans la table ETIQ_PC
INSERT INTO ETIQ_PC (NUM_ETIQ, NUM_PC, DATE_DEBUT, DATE_FIN) VALUES 
('ETIQ1', 'PC1', '2022-01-01', '2022-01-31'),
('ETIQ2', 'PC2', '2022-02-01', '2022-02-28');

-- Insertion de données dans la table ANTENNE
INSERT INTO ANTENNE (ID_ANTENNE, EMPLACEMENT, DATE_DEBUT, DATE_FIN) VALUES 
('ANT1', 'Emplacement1', '2022-01-01', '2022-01-31'),
('ANT2', 'Emplacement2', '2022-02-01', '2022-02-28');

-- Insertion de données dans la table users via le fichier register.php

